### ISSUE TITLE
Intuos Pro M crashes Cinnamon control center after selecting the Graphics Tablet option.

### ISSUE THREAD

**Issue by EzraT** [linuxmint/cinnamon-control-center#212]
**cinnamon-control-center: 3.8.1**
**Linux Mint 19: Tara - 64bit**
**Nvidia GTX 1060 6GB on driver version: 390.48**

Not sure if this is the right location for Wacom related issues, but here it goes anyway,
I am trying to configure a Wacom Intuos Pro M graphics tablet on a fresh installation of Linux Mint 19.
Cinnamon control center crashes immediately after clicking on the Graphics Tablet option in the menu.
When I run "cinnamon-settings wacom" in a terminal window, the output is as follows:

```
Using PAM module (python3-pam)
**
wacom-cc-panel:ERROR:csd-wacom-device.c:242:csd_wacom_stylus_get_stylus_type: code should not be reached
Aborted (core dumped)
```
The tablet connects and is recognized, as shown by this xsetwacom --list devices output:

```
Wacom Intuos Pro M Pad pad      	id: 14	type: PAD
Wacom Intuos Pro M Pen stylus   	id: 15	type: STYLUS    
Wacom Intuos Pro M Pen eraser   	id: 16	type: ERASER    
Wacom Intuos Pro M Pen cursor   	id: 17	type: CURSOR    
Wacom Intuos Pro M Finger touch 	id: 18	type: TOUCH     
```

But obviously cannot be configured in the UI because the control center crashes.

**Steps to reproduce**
1, Connect the Intuos Pro M.
2, Open Cinnamon control center.
3, Select Graphics Tablets.

**Other information**
All the wacom driver packages are installed on my system for as far as I can see.
When the tablet is unplugged, the UI loads up like it should.

**Comment by mtwebster** [comment]
Is this the Pro Medium?  I'm looking to purchase an up-to-date model to try to troubleshoot some of the tablet issues I've seen on the forums.  I just want to be sure I get one that matches something people have issues with.

This is the one I was looking at: https://us-store.wacom.com/Catalog/Pen-Tablets/Intuos-pro/wacom-intuos-pro#/undefined1

Thanks

**Comment by mtwebster** [comment]
Ok should be fixed by https://github.com/linuxmint/cinnamon-control-center/commit/0c5cbb16890fa2767a12e657719a97d9d2edd584

I'll see about getting an update out.

**Comment by EzraT** [comment]
Thank you! I'll test it as soon as I notice it updating.

**Comment by Necco-Z** [comment]
I suggest re-opening this, as I'm still having this issue. I'm running Cinnamon v. 4.2.4 on Manjaro on a laptop and a PC, and in both I experience the same problem.

xinput --list:
> ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
> ⎜   ↳ Logitech Wireless Mouse                 	id=10	[slave  pointer  (2)]
> ⎜   ↳ Atmel Atmel maXTouch Digitizer          	id=14	[slave  pointer  (2)]
> ⎜   ↳ ETPS/2 Elantech Touchpad                	id=17	[slave  pointer  (2)]
> ⎜   ↳ Wacom Intuos S Pad pad                  	id=11	[slave  pointer  (2)]
> ⎜   ↳ Wacom Intuos S Pen stylus               	id=12	[slave  pointer  (2)]
> ⎜   ↳ Wacom Intuos S Pen eraser               	id=18	[slave  pointer  (2)]
> ⎜   ↳ Wacom Intuos S Pen cursor               	id=19	[slave  pointer  (2)]
> ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
>     ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
>     ↳ Asus Wireless Radio Control             	id=6	[slave  keyboard (3)]
>     ↳ Video Bus                               	id=7	[slave  keyboard (3)]
>     ↳ Power Button                            	id=8	[slave  keyboard (3)]
>     ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
>     ↳ USB2.0 HD UVC WebCam: USB2.0 HD         	id=13	[slave  keyboard (3)]
>     ↳ Asus WMI hotkeys                        	id=15	[slave  keyboard (3)]
>     ↳ AT Translated Set 2 keyboard            	id=16	[slave  keyboard (3)]

lsusb:
> Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 005: ID 03eb:881a Atmel Corp. 
> Bus 001 Device 003: ID 04f2:b354 Chicony Electronics Co., Ltd UVC 1.00 device HD UVC WebCam
> Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 002 Device 004: ID 056a:0374 Wacom Co., Ltd CTL-4100 [Intuos (S)]
> Bus 002 Device 002: ID 046d:c534 Logitech, Inc. Unifying Receiver
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Running cinnamon-control-center from terminal I get the following error when I try to open the Graphics Tablet option:

> (cinnamon-settings.py:1986): wacom-cc-panel-WARNING **: 13:15:27.382: Could not set the current stylus ID 0x0 for tablet 'Wacom Intuos S', no general pen found
> **
> wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
> Bail out! wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)

**Comment by mtwebster** [comment]
I can't reproduce that with my Pro M, even after updating to the latest libwacom (1.1) and xf86-wacom (.38) - can you confirm these are the versions you're on?  Did the tablet work before at some point? It looks like those two versions are quite recent, in the past month or so.

**Comment by Necco-Z** [comment]
libwacom is version 1.1 and I believe you're talking about xf86-input-wacom, mine is v 0.37, tried updating and a new version didn't show up. But in case there was some confusion: the tablet does work, but it's impossible to configure it using the UI at the control center.

**Comment by wujastyk** [comment]
Linux NNN 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 20, Cinnamon 4.6.6
Wacom Intuos S tablet.

Same problem as Necco-Z

**Comment by dm2912** [comment]
for the Intuos S

Edit **/usr/share/libwacom/intuos-s-p3.tablet** and change the line **Styli=@intuospt3;** to **Styli=@intuospt3;0xffffe;**

for me I have just taken to writing bash scripts for various configs, so for example for Gimp

```
#! /bin/bash
## Setup Wacom buttons for Gimp
## Pad
xsetwacom set "$PAD" Button 1 "key shift plus"  # Zoom in
xsetwacom set "$PAD" Button 2 "key minus"  # Zoom out
xsetwacom set "$PAD" Button 3 "key p"  # Paintbrush
xsetwacom set "$PAD" Button 8 "key a"  # Airbrush
# Pen
xsetwacom --set "Wacom Intuos S Pen stylus" Button 2 2 # Middle Mouse Button
xsetwacom --set "Wacom Intuos S Pen stylus" Button 3 "key control z"  # Undo
#Pressure
xsetwacom set "Wacom Intuos S Pen stylus" PressureCurve 0 30 70 100
```

**Comment by wujastyk** [comment]
That "0xffffe;" worked.  Complete black magic to me :-)

Thank you so much!

Dominik

**Comment by JaviMaciasG** [comment]
I am having the same problem with an Intuos BT M, running cinnamon-control-center 4.4.0 on a fresh install of ubuntu 20.04. I get similar behaviour than that reported by @csbenjamin above. More details:


# When connected with the USB:
- When entering the tablet-related section of the control-center crashes 
- The tablet is "usable", but the full screen width area is covered with the stylus moving in roughly 1/3 of the tablet width
- cinnamon-settings output
```
macias@mowgli:~$ cinnamon-settings tablet
True
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:427: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)

(cinnamon-settings.py:21540): libwacom-WARNING **: 08:37:27.953: Invalid prefix for ''!

(cinnamon-settings.py:21540): wacom-cc-panel-WARNING **: 08:37:27.962: Could not set the current stylus ID 0x0 for tablet 'Wacom Intuos BT M (Android Mode)', no general pen found
**
wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Bail out! wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Abortado (`core' generado)
```
  - xsetwacom output (note that no "Pad" is detected)
```
macias@mowgli:~$ xsetwacom --list devices
Wacom Co.,Ltd. Intuos BT M stylus	id: 27	type: STYLUS    
Wacom Co.,Ltd. Intuos BT M eraser	id: 28	type: ERASER    
```

  - And finally, the report from  libwacom-list-local-devices, (note that it states "Android Mode" in the device name, and "Width=3"):

```
macias@mowgli:~$ libwacom-list-local-devices > wacom-bluetooth.txt 

(libwacom-list-local-devices:26509): libwacom-WARNING **: 09:36:21.596: Invalid prefix for ''!
# Device node: /dev/input/event28
[Device]
Name=Wacom Intuos BT M (Android Mode)
ModelName=CTL-6100WL
DeviceMatch=usb:2d1f:0378;
Class=Bamboo
Width=3
Height=5
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```

# When connected through bluetooth:
- The control center for the tablet does not crash, and the tablet to screen position mapping is correct.
- xsetwacom output (now the "Pad" is detected)

```
macias@mowgli:~$ xsetwacom --list devices
Wacom Intuos BT M Pen stylus    	id: 27	type: STYLUS    
Wacom Intuos BT M Pad pad       	id: 28	type: PAD       
```
  - The report from libwacom-list-local-devices is (now two devices appear, there is no reference to "Android mode", and note the "Width=9"):

```
macias@mowgli:~$ libwacom-list-local-devices

(libwacom-list-local-devices:26660): libwacom-WARNING **: 09:38:37.625: Invalid prefix for ''!
# Device node: /dev/input/event29
[Device]
Name=Wacom Intuos BT M
ModelName=CTL-6100WL
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=9
Height=5
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
# Device node: /dev/input/event28
[Device]
Name=Wacom Intuos BT M
ModelName=CTL-6100WL
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=9
Height=5
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=4

[Buttons]
# Left=
# Right=
Top=A;B;C;D;
# Bottom=
# Touchstrip=
# Touchstrip2=
# OLEDs=
# Ring=
# Ring2=
EvdevCodes=0x110;0x111;0x115;0x116;
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

---------------------------------------------------------------
```
Additional details:

- I tried the magic solution by @dm2912 above without success (in the /usr/share/libwacom/intuos-m-p3.tablet file, which I believe is the one corresponding to the Intuos BT M)

Thank you very much!!

**Comment by JaviMaciasG** [comment]
Minor update to my previous posting:

I just discovered that, for the Intuos BT M, the files to modify with the solution by @dm2912 are intuos-m-p3-wl-android.tablet and intuos-m-p3-wl.tablet (the model number is CTL-6100WL, the same than the one referred to in these files).

I still have no solution for the wrong width detection when connecting by USB.

**Comment by JaviMaciasG** [comment]
Hi again!

I was just digging a bit and I found the solution to the wrong width detection at https://github.com/linuxwacom/xf86-input-wacom/wiki/Known-Issues#android-misdetect

The problem is that the wacom is detected as "Android mode", and to switch it back to "PC mode" you just have to hold down the two outermost ExpressKeys for 3-4 seconds. I works like a charm!

**Comment by bryanhoffman04** [comment]
```
cinnamon-settings wacom
Xlib:  extension "DPMS" missing on display ":100".
**
wacom-cc-panel:ERROR:csd-wacom-device.c:242:csd_wacom_stylus_get_stylus_type: code should not be reached
Aborted (core dumped)
```
-----------------------
That's the error I'm currenting getting.   If I cat the 'intuos-pro-m.tablet' file `Styli=` looks like below:

Styli=0x802;0x804;0x806;0x80a;0x80c;0x902;0x90a;0x100802;0x100804;0x10080a;0x10080c;0x100902;0x10090a;0x120802;0x140802;0x14080a;0x160802;0x16080a;


Haven't found a working solution yet.  
I've tried adding:
0x862;   
0xffffe; 
0x862;0xffffe;
